version: '3'

services:
  dev:
    build:
      context: .
    ports:
      - 3000:3000
    command: yarn start --host 0.0.0.0
  test:
    build:
      context: .
    environment:
      - CI=true
    command: yarn test --colors
