version: 2
jobs:
  build:
    docker:
      - image: circleci/node:erbium

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test
        environment:
          JEST_JUNIT_OUTPUT_DIR: "test-reports/test-results.xml"
      - run: yarn lint
      - run: yarn test:coverage

      - store_artifacts:
          path: ~/repo/coverage

      - store_test_results:
          path: ~/test-reports
