version: 2
jobs:
  build:
    docker:
      - image: circleci/node:erbium

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run tests
          command: yarn test --ci --runInBand
      - run: yarn lint
      - run: yarn test:coverage

      - store_artifacts:
          path: ~/repo/coverage

      - store_test_results:
          path: ~/repo/test-report
